all:	interface noise_maker

interface:	interface.c
	gcc -Wall -ggdb -o interface interface.c

noise_maker:	noise_maker.c
	gcc -Wall -ggdb -o noise_maker noise_maker.c

clean:
	rm interface noise_maker


