all:	interface2 noise_maker

interface2:	interface2.c
	gcc -Wall -ggdb -o interface2 interface2.c

noise_maker:	noise_maker.c
	gcc -Wall -ggdb -o noise_maker noise_maker.c

clean:
	rm interface2 noise_maker
