all: fork_ex execvp_ex wait_ex my_shell4

fork_ex: fork_ex.c
	gcc -o fork_ex fork_ex.c

execvp_ex: execvp_ex.c
	gcc -o execvp_ex execvp_ex.c

wait_ex: wait_ex.c
	gcc -o wait_ex wait_ex.c

my_shell4: my_shell4.c
		gcc -o my_shell4 my_shell4.c

clean:
	rm my_shell4 wait_ex execvp_ex fork_ex
