all:	my_shell2 getline1 getline2

my_shell2:	my_shell2.c
	gcc -o my_shell2 my_shell2.c

getline1:	getline1.c
	gcc -o getline1 getline1.c

getline2:	getline2.c
	gcc -o getline2 getline2.c

clean:
	rm my_shell2 getline1 getline2


